name: Pelican Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican markdown ghp-import

    - name: List directory contents
      run: |
        ls -la

    - name: Build Pelican site
      run: |
        pelican content -o output -s pelicanconf.py

    - name: Configure Git for GitHub Pages deployment
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"
        git remote rm origin
        git remote add origin https://${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Deploy to GitHub Pages
      run: |
        ghp-import -n -f output
        git remote set-url --push origin "https://${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository }}"
        git push -f origin gh-pages
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}


