name: Pelican Build and Deploy

on:
  push:
    branches:
      - gh-pages

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican markdown ghp-import

    - name: Build Pelican site
      run: |
        pelican content -o output -s pelicanconf.py

    - name: Deploy to GitHub Pages
      run: |
        ghp-import -n -p -f output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
